// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGRf4ZcEjy0R88q8yntdoSCbmpbAZySFo',
    appId: '1:609296103465:web:bd935e08e798c658b58438',
    messagingSenderId: '609296103465',
    projectId: 'app2-ce32b',
    authDomain: 'app2-ce32b.firebaseapp.com',
    storageBucket: 'app2-ce32b.appspot.com',
    measurementId: 'G-SXTWS73C91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz3Xb15E3BDjrBIFb1V7wDXccGiwmT3ww',
    appId: '1:609296103465:android:f5fbda8725b4968db58438',
    messagingSenderId: '609296103465',
    projectId: 'app2-ce32b',
    storageBucket: 'app2-ce32b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvexZbR_ROP1Y6_jZCgraLlLVX2I9UddQ',
    appId: '1:609296103465:ios:9ca3c69aa710e0c7b58438',
    messagingSenderId: '609296103465',
    projectId: 'app2-ce32b',
    storageBucket: 'app2-ce32b.appspot.com',
    iosBundleId: 'com.example.app2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvexZbR_ROP1Y6_jZCgraLlLVX2I9UddQ',
    appId: '1:609296103465:ios:ff9037f40b074c94b58438',
    messagingSenderId: '609296103465',
    projectId: 'app2-ce32b',
    storageBucket: 'app2-ce32b.appspot.com',
    iosBundleId: 'com.example.app2.RunnerTests',
  );
}
